# Provide all paths where automated discovery should be performed.
[[paths]]
path = "projects/"  # All paths are relative to your home directory.

[[paths]]
path = "work/"

# Not only project directories can be provided.
# You can also provide paths specific to your local setup.
# E.g., if you collect all virtualenvs in a separate directory.
# It's suitable for tools like virtualenvwrapper or Poetry.
[[paths]]
path = ".virtualenvs/"
